name: Build with Legacy APK

on:
  workflow_dispatch:

jobs:
  build_and_deploy_android_firebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: RN setup
        run: |
          yarn add global react-native-cli;
          cd package
          yarn;
          cd native-package
          yarn;
          cd ../../examples/SampleApp
          yarn;
      - name: Build
        run: |
          cd examples/SampleApp
          mkdir android/app/src/main/assets
          mkdir tmp
          yarn react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest tmp
          cd android
          rm -rf $HOME/.gradle/caches/ && ./gradlew assembleRelease

      - name: Upload Artefacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: examples/SampleApp/android/app/build/outputs/apk/release/app-release.apk
#      - name: Deploy
#        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
#        with:
#          appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}
#          token: ${{secrets.FIREBASE_TOKEN}}
#          groups: android-react-native-testers
#          file: examples/SampleApp/android/app/build/outputs/apk/release/app-release.apk
