name: sample-distribution

concurrency:
  group: sample-distribution-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  build_and_deploy_android_s3:
    name: Build SampleApp Android and Deploy-${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
          check-latest: true
      - name: Install && Build - SDK and Sample App
        uses: ./.github/actions/install-and-build-sdk
      - name: Build
        run: |
          cd examples/SampleApp
          mkdir android/app/src/main/assets
          mkdir tmp
          yarn react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest tmp
          cd android
          rm -rf $HOME/.gradle/caches/ && ./gradlew assembleRelease

      - name: Upload Artefacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: examples/SampleApp/android/app/build/outputs/apk/release/app-release.apk

      # - name: Configure AWS credentials
      #  uses: aws-actions/configure-aws-credentials@v1
      #  if: ${{ github.ref == 'refs/heads/develop' }}
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws-region: us-east-1
      #- name: Upload APK
      #  if: ${{ github.ref == 'refs/heads/develop' }}
      #  # https://getstream.io/downloads/rn-sample-app.apk
      #  run: |
      #    cp examples/SampleApp/android/app/build/outputs/apk/release/app-release.apk rn-sample-app.apk
      #    aws s3 cp rn-sample-app.apk s3://${{ secrets.AWS_S3_BUCKET }} --sse AES256
